"""
Django settings for turnero project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from dotenv import load_dotenv
import os

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

def _get_bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


# ===============================
# Google Calendar – Nueva lógica
# ===============================

GOOGLE_CREDENTIALS_FILE = BASE_DIR / "credentials" / "credentials.json"
GOOGLE_TOKEN_FILE = BASE_DIR / "credentials" / "token.json"
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
    "GOOGLE_OAUTH_REDIRECT_URI",
    "https://175galindez.pythonanywhere.com/oauth2/callback",
)
GOOGLE_OAUTH_SCOPES = [
    "https://www.googleapis.com/auth/calendar",
]

# Calendario BD (fuente de verdad de TODOS los slots)
GOOGLE_CALENDAR_BD_ID = os.getenv(
    "GOOGLE_CALENDAR_BD_ID",
    "c5f24b9cb8afda0c0895c043a75f96252137179bf037b11efbafa043135fdc30@group.calendar.google.com",
)

# Timezone de trabajo
CALENDAR_TIMEZONE = "America/Santiago"



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-mcsml#gl*)**n01z468wqq5u%$nvlcrigv^v!7hp_o_*50#*s%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env("DEBUG", True)

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOST", "").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'calendar_app',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'turnero.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'turnero.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


CACHES = {
  "default": {
    "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    "LOCATION": "turnero-cache"
  }
}

# ===============================
# Configuración de Sesiones (OAuth)
# ===============================
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Usar BD para persistencia
SESSION_SAVE_EVERY_REQUEST = True  # Guardar sesión en cada request
SESSION_COOKIE_SAMESITE = "Lax"  # Permitir redirect externo (Google OAuth)
SESSION_COOKIE_SECURE = False  # False para localhost (True en producción HTTPS)
SESSION_COOKIE_AGE = 3600  # 1 hora suficiente para completar OAuth


SPECTACULAR_SETTINGS = {
    'TITLE': 'API Turnero',
    'DESCRIPTION': 'Documentación de la API',
    'VERSION': '1.0.0',

    'SERVE_INCLUDE_SCHEMA': False,

    # ✅ Oculta estos endpoints "internos" del schema exportado
    'EXCLUDE_PATHS': [
        r'^/api/schema/?$',
    ],

    # ✅ URL base para Dialogflow Tools y clientes externos
    'SERVERS': [
        {'url': 'https://175galindez.pythonanywhere.com', 'description': 'Producción'},
    ],
}

